### ISSUE TITLE
For info, I think can install torch-hdf5 as `hdf5`?

### ISSUE THREAD

**Issue by hughperkins** [jcjohnson/torch-rnn#1]
Hi justin,

Nice library :-)

For hdf5, seems like one can install it using `luarocks install hdf5`?  This will install: https://raw.githubusercontent.com/torch/rocks/master/hdf5-20-0.rockspec , which I think brings down latest `master` branch?

**Comment by jcjohnson** [comment]
Thanks! It was a fun weekend project.

I've always been leery to install hdf5 via luarocks because of [the warning on their usage page](https://github.com/deepmind/torch-hdf5/blob/master/doc/usage.md), but `luarocks install hdf5` does seem to grab the right package.

**Comment by hughperkins** [comment]
Ah, interesting.  Hmmm. Might depend on which rocks servers one is using.... hmmm

**Comment by jcjohnson** [comment]
Yeah seems confusing ... seems safer just to explicitly get it from their GitHub repo.

**Comment by hughperkins** [comment]
Yes, agree.
