### ISSUE TITLE
How do I sample with this? 

### ISSUE THREAD

**Issue by LucNaterop** [jcjohnson/torch-rnn#110]
With the VanillaRNN, the call `h = rnn:forward({h0, x}) ` gives me the hidden state, but what about the predictions (or outputs) of the RNN? How can I obtain them? Shouldn't `forward()` be implemented such that it returns them, too?

**Comment by jcjohnson** [comment]
You can sample by using the `sample` method of a `LanguageModel`:

https://github.com/jcjohnson/torch-rnn/blob/master/LanguageModel.lua#L148

The RNN classes (VanillaRNN, LSTM) are intended to be generic and usable for any application, so they only process sequences of hidden states and don't know anything about sampling. Modeling language is one common use case for an RNN, so all logic specific to language modeling is in the `LanguageModel` class.

**Comment by gokceneraslan** [comment]
If you don't set up a gitter room or google groups, people will keep asking questions here Justin.
