### ISSUE TITLE
module 'bit' not found:No LuaRocks module found for bit

### ISSUE THREAD

**Issue by RobertMolesme** [jcjohnson/torch-rnn#127]
I'm getting this error when trying to run train.lua, what can I do?

`box:torch-rnn-master jules$ th train.lua -input_h5 tiny-shakespeare.h5 -input_json my_data.json
/Users/jules/anaconda/bin/lua: /Users/jules/anaconda/share/lua/5.3/trepl/init.lua:384: /Users/jules/anaconda/share/lua/5.3/trepl/init.lua:384: /Users/jules/anaconda/share/lua/5.3/trepl/init.lua:384: module 'bit' not found:No LuaRocks module found for bit
	no field package.preload['bit']
	no file '/Users/awiltschko/.luarocks/share/lua/5.3/bit.lua'
	no file '/Users/awiltschko/.luarocks/share/lua/5.3/bit/init.lua'
	no file '/Users/jules/anaconda/share/lua/5.3/bit.lua'
	no file '/Users/jules/anaconda/share/lua/5.3/bit/init.lua'
	no file '/Users/jules/anaconda/lib/lua/5.3/bit.lua'
	no file '/Users/jules/anaconda/lib/lua/5.3/bit/init.lua'
	no file './bit.lua'
	no file './bit/init.lua'
	no file '/Users/jules/.luarocks/share/lua/5.3/bit.lua'
	no file '/Users/jules/.luarocks/share/lua/5.3/bit/init.lua'
	no file '/Users/awiltschko/.luarocks/lib/lua/5.3/bit.so'
	no file '/Users/jules/anaconda/lib/lua/5.3/bit.so'
	no file '/Users/jules/anaconda/lib/lua/5.3/loadall.so'
	no file './bit.so'
	no file '/Users/jules/.luarocks/lib/lua/5.3/bit.so'
stack traceback:
	[C]: in function 'error'
	/Users/jules/anaconda/share/lua/5.3/trepl/init.lua:384: in function 'require'
	train.lua:6: in main chunk
	[C]: in function 'dofile'
	/Users/jules/anaconda/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?`

Thanks!

**Comment by RobertMolesme** [comment]
Apparently it has something to do with the fact luabitop is not compatible with lua 5.3, any suggestions?

**Comment by jcjohnson** [comment]
I've never used Lua 5.3 so I'm not sure - I guess the easy solution is to
downgrade to Lua 5.2.

**Comment by RobertMolesme** [comment]
Alright, thanks!

**Comment by lonevetad** [comment]
Hi,
i'm using Lua 5.3.3 and i have to do bitwise operations, such as ">>" (right shift) and "&" (and) like Java or C.
Initially, i used them as the manual shows, but the parser told me that an unexpected symbol was found near ">" ... so i changed to the relative function, but Lua cannot find package "bit" !!!
Any suggestions, please?

**Comment by dagisky** [comment]
I faced the same problem with lua 5.2.3 :/
