### ISSUE TITLE
Word vs character mode

### ISSUE THREAD

**Issue by RobertMolesme** [jcjohnson/torch-rnn#134]
Is there any way of doing the training using words instead of characters as the basic unit of the model?

**Comment by smartynov** [comment]
I was able to achieve this quite easily by changing preprocessing script. Initially it maps characters to numeric values, I altered it so it can split input into words, not characters. You can take a look at https://github.com/smartynov/torch-rnn/blob/master/scripts/preprocess.py

When running preprocessing, use `--tokenize word` flag:
```bash
python $scripts/preprocess.py --input_txt data/tiny-shakespeare.txt --output_h5 data/tiny_shakespeare.h5 --output_json data/tiny_shakespeare.json --tokenize word
```

The downside is that currently there is no way to provide `-start_text` when sampling. Other further improvements may include better whitespace and punctuation treatment, better support for word capitalisation and so on.

**Comment by dgcrouse** [comment]
See my pull request. I add extensive word-based support and support to cull words that are infrequent. It can even handle a folder of documents (currently limited to .txt extension for identification by the script) and cull words that appear in fewer than n documents. Check out my branch for even more features than are in the pull request.

**Comment by RobertMolesme** [comment]
This is great, I'm gonna give it a go!

Cheers
