### ISSUE TITLE
expected align(#) on line 579

### ISSUE THREAD

**Issue by kishu0495** [jcjohnson/torch-rnn#145]
when i type --> require 'hdf5';
output is ->

th> require 'hdf5'
/home/kishu/torch/install/share/lua/5.2/trepl/init.lua:384: /home/kishu/torch/install/share/lua/5.2/hdf5/ffi.lua:56: expected align(#) on line 579
stack traceback:
    /home/kishu/torch/install/share/lua/5.2/trepl/init.lua:501: in function </home/kishu/torch/install/share/lua/5.2/trepl/init.lua:494>
    [C]: in function 'error'
    /home/kishu/torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
    [string "_RESULT={require 'hdf5'}"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/kishu/torch/install/share/lua/5.2/trepl/init.lua:652: in function 'repl'
    ...ishu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: in ?

**Comment by kishu0495** [comment]
I have ubuntu 16.04  and lua version is 5.2.3.

**Comment by jcjohnson** [comment]
It seems that this is a problem with the torch-hdf5 package running under Lua 5.2; if possible you should use luajit:

https://github.com/deepmind/torch-hdf5/issues/79

**Comment by HuiJiongYang** [comment]
I meet the same problem,so is there any solution here？
when i install torch-hdf5,there is a problem with: could not satisfy dependency:totem
and then install torch-totem,a problem with:could not satisfy dependency:nngraph
next,i install nngraph :sudo ~/torch/install/bin/luarocks install nngraph
when ended,it display:nngraph scm-1 is now built and installed in ./torch/install/ (license: UNKNOWN)
but when i run:sudo luarocks make in directory rorch-totem,the same problem with "could not satisfy dependency:nngraph" is also there.
