### ISSUE TITLE
Fine tuning?

### ISSUE THREAD

**Issue by rossgoodwin** [jcjohnson/torch-rnn#147]
I tried fine tuning my LSTM model by starting at a predefined checkpoint and switching the input corpus for a smaller text file with the same vocabulary size. After training for a few epochs, the output looked like this:

> Ofk Aoc?km |i Ofk WcOOkom f|m mOcomtnciu afki Ofk fc?k fko fkcu fko f|m fkcum rd fko fkcoOna|Of ekO Ofk aceem WecSkn|i Ofk orr
>  a|Of bkmO |i Ofk fkcu rd Srleu Ofk mkcOf a|Of Ofk rlomknOfk mOcom rd Ofk mOcium Ofk urik fko e|Fk c WcoO|iA rd Ofk Scoo|ku Ofk urainciu ciu Ofk d|iAkom Sermku Ofk acm mkcem rd Ofk d|kmNn; mOrik rd Ofk mc
> k |i Ofk bloi|iA Ofk ukmOoramtnmfk a|Of Ofk dokkvu cee c mf|iA rd c bloiku ciu Ofk d|oknOfk mrliu Ofk mc|u ciu Ofk mOro
> nOfk aroeu Ofk srlo berru Ofk WcoO rd Ofk mciuNn; Ofk mOcou Ofk mli ukGO blO ciu Ofk mOcom |i Ofk Sr
> WerO|riNnwiu Ofk So|km fc?k Ofk brus |i Ofk OrrF ciu mOcoO rd Ofk mcmO Ofk blO afki Ofk bo|iA rd Ofk dro Ofk bo|iAmnciu fcu Ofk bkSclmk bkki Ofk 
> roi|iA Ofk
> nciu Ofk mr
> kOf|iA bs Ofk mriA Ofk SciirO Ofk AokcO rd c aroeu mOcomnfko u|mOkoiku ciu Ofk dro dcSkm a|Of Ofk mWcSknOfk mOcoO Ofk d|omO ciu Ofk Scokm cok cm Aokki rd ciu Ofk AocWkmn|i Ofk mOokkOm rd Ofk mr
> kOf|iA bokcFm ciu Ofk borFki mfk Ofk mli Ofk bcSF rd Ofk Ooc|im rd Ofk OrrF ciu SfkkWNnjfr mfrleu rd Ofk ekc?km Ofk e|AfO mOcium ciu cok Ofk k?kos ciu WokmkiONnjfcO Ofk o|AfO f|m ecOko 
> cFk Ofk mO|ee Ofk dcSk rd Ofk WcoOloktnciu Ofk 

Guessing I'm not fine tuning correctly. Any advice on how to do that with Torch-RNN? Is there a way to make it work?

**Comment by jcjohnson** [comment]
That's not really a use-case I had in mind.

If you want to make this work, you'll need to match not only the sizes of the two vocabularies but also the orders.

**Comment by rossgoodwin** [comment]
Thanks! Does that mean the smaller file could just be the first N lines of the larger file?

**Comment by vintermann** [comment]
This is one way torch-rnn differs from char-rnn. Char-rnn sorts the character mapping before saving it (https://github.com/karpathy/char-rnn/blob/master/util/CharSplitLMMinibatchLoader.lua#L151), so assuming they use _exactly_ the same alphabet, you can train it first on one file and finish it off on another.

As I recall, torch-rnn maps the characters according to the order it first encounters them. So a user-side hack is to make sure the first line in both files 

1. contains all characters present in the file(s)
2. in the same order

It should be easy enough to change the source to skip this, really, but I think that would break compatibility with existing checkpoints.
