### ISSUE TITLE
classification?

### ISSUE THREAD

**Issue by ianni67** [jcjohnson/torch-rnn#151]
I'm on my way to implementing a classification application and would love to receive any hints.
I'm experimenting with torch-rnn and my plans are to extend sample.lua in order to be able to classify text according to a given number of classes, such as (for example) Shakespeare, Asimov, Rowling, G. W. Bush. I would train a net with text samples from each class (plus an "unknown" class to rule out text excerpts that do not belong to any of the other classes) and then let the net try to assign new text  excerpts to the learned classes. 
This would probably represent an interesting evolution of torch-rnn, and if I make it, I'll release my code here (either as a branch or requesting a pull), so please any advice will be useful.

**Comment by LuZhenHuan** [comment]
hello，if you want to solve a classification problem with torch-rnn, how to build a many to one model? 1 sequence match one label, not one word match on label.

**Comment by ianni67** [comment]
hello,
after some months I moved to a different architecture. 
Anyway, thank you for the hint. The first and the only one I got ;-)
