### ISSUE TITLE
error when running train.lua using  a small dataset : ./util/DataLoader.lua:35: in function '__init'

### ISSUE THREAD

**Issue by brisker** [jcjohnson/torch-rnn#161]
Hi, I follow the instructions but why the train.lua gives me this error?
jcc@jcc:~/torch-rnn$ th train.lua -input_h5 my_data.h5 -input_json my_data.json
Running with CUDA on GPU 0
/home/jcc/torch/install/bin/luajit: bad argument #2 to '?' (end index out of bound at /home/jcc/torch/pkg/torch/generic/Tensor.c:992)
stack traceback:
[C]: at 0x7f91bfdef4d0
[C]: in function '__index'
./util/DataLoader.lua:35: in function '__init'
/home/jcc/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/jcc/torch/install/share/lua/5.1/torch/init.lua:87>
[C]: in function 'DataLoader'
train.lua:76: in main chunk
[C]: in function 'dofile'
.../jcc/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00406670
Help ?

**Comment by wordandahalf** [comment]
I receive this error as well.

**Comment by shibhansh** [comment]
@brisker  how was this issue solved ? I'm getting the same error.
