### ISSUE TITLE
Unable to locate HDF5 Header

### ISSUE THREAD

**Issue by Collinthegeek** [jcjohnson/torch-rnn#170]
I get 
`$ th train.lua -input_h5 data/tweets.h5 -input_json data/tweets.json
/home/cnorwood/torch/install/bin/luajit: /home/cnorwood/torch/install/share/lua/5.1/trepl/init.lua:389: /home/cnorwood/torch/install/share/lua/5.1/trepl/init.lua:389: /home/cnorwood/torch/install/share/lua/5.1/hdf5/ffi.lua:42: Error: unable to locate HDF5 header file at hdf5.h
stack traceback:
	[C]: in function 'error'
	/home/cnorwood/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:6: in main chunk
	[C]: in function 'dofile'
	...wood/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405760
`
On Fedora 25
I have hdf5 and hdf5-devel installed

**Comment by Collinthegeek** [comment]
fixed

**Comment by chidg** [comment]
@Collinthegeek, could you please tell us how you fixed it? I'm having the same issue.
