### ISSUE TITLE
Errors running train.lua

### ISSUE THREAD

**Issue by grishmarao** [jcjohnson/torch-rnn#173]
Hello, I'm trying to train my first torch-rnn, followed all the install steps as per this tutorial: http://www.jeffreythompson.org/blog/2016/03/25/torch-rnn-mac-install/

My training data is preprocessed by the script, but whenever I try to run train.lua I get errors like this:

```
th train.lua -input_h5 data/sad.h5 -input_json data/sad.json -gpu -1
/Users/Apple/torch/install/bin/luajit: /Users/Apple/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/Apple/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/Apple/torch/install/share/lua/5.1/hdf5/config.lua:2: unexpected symbol near 'local'
stack traceback:
	[C]: in function 'error'
	/Users/Apple/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:6: in main chunk
	[C]: in function 'dofile'
	...pple/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0103a24bd0
```

Please help :) I've tried uninstalling and reinstalling, but haven't been able to ever run train.lua

**Comment by dgcrouse** [comment]
It looks like you're missing a dependency. Error is in an external library and is related to an external tutorial, so I'm going to go ahead and close it.
