### ISSUE TITLE
requirements.txt installation: "no such file or directory"

### ISSUE THREAD

**Issue by Wrongful** [jcjohnson/torch-rnn#175]
Hello!
I'm trying to get this program to work, and after much frustration with the installation of the required packages, I think I finally have installed everything I need except for the requirements file. I preformed the instructions that were there, but they didn't work due to "no such file or directory" existing.
I have downloaded the zip file for this program, so I have the requirements.txt file on my desktop, so where do I put it for the program to know it's there?
(I'm new to Ubuntu, sorry if this is obvious.)

**Comment by ChrisCummins** [comment]
The installation instructions assume you are in the directory that you cloned this repo to. So:

```
git clone git@github.com:jcjohnson/torch-rnn.git ~/torch-rnn
cd ~/torch-rnn
# proceed as before
```

**Comment by Wrongful** [comment]
Thank you for the help, it appears to be working, but...
`Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have correct access rights
and the repository exists.`
I'm sure I spelled everything right, so it must be the access rights. How do I solve this?
(This is all newbie stuff, isn't it...)

**Comment by ChrisCummins** [comment]
Sorry yep, I gave you the wrong URL

**Comment by ChrisCummins** [comment]
Marking this as solved.
