### ISSUE TITLE
Preprocessor breaks on non-UTF8 input

### ISSUE THREAD

**Issue by qwertystop** [jcjohnson/torch-rnn#176]
The preprocessor script fails to run when the input file is not valid UTF8. Given that the algorithms involved, to the best of my understanding, ought to work on any ordered collection of bytes, this seems like a bug.

**Comment by antihutka** [comment]
Use `--encoding bytes` to switch to byte encoding. This isn't properly supported in the sampling script, but that's easy to fix.

**Comment by qwertystop** [comment]
Well, that'll teach me to file issues at two-in-the-morning. Thanks. Not closing this yet; I have an idea to make the script work for multi-byte "characters" of no particular encoding.

**Comment by qwertystop** [comment]
Never mind prior comment; closing this, any such improvement would be a PR.
