### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by ChrisCummins** [jcjohnson/torch-rnn#178]
Hi @jcjohnson,

It seems you've moved on to other projects. Please consider asking for volunteers to help maintain this project. There is a backlog of pull requests and a bug tracker is becoming swamped with stale non-issues. This is a popular repo, it would be a shame for it to stagnate.

I would be happy to volunteer, as I'm sure would others.

Cheers,
Chris

**Comment by dgcrouse** [comment]
I will also volunteer. I maintain a fork of the project with lots of new features which I'd love to bring to the main repo.

I've got lots of ideas for the project to merge from my fork (some of which came from other forks as well) such as:

- CUDNN support
- Support for folders of text files
- Support for word tokens
- Support for specifying checkpoints by epoch
- Overhaul of the checkpointing system, including a full resume system so you can pause training/recover from a system crash
- Support for LevelDB/LMDB for much faster I/O (in progress)

**Comment by qwertystop** [comment]
As yet I have insufficient knowledge of the codebase or the research behind it to volunteer as a maintainer, but if it gets this running smoothly I am willing to volunteer to at least chip in around the edges where I can.

**Comment by dgcrouse** [comment]
Since it has been almost a month with no response, I move that we create a fork of the project to keep current. If and when @jcjohnson responds to this issue we can merge changes back in. All we need is a way to get publicity to the fork, maybe Hacker News?

**Comment by jcjohnson** [comment]
Sorry for the slow responses - You are all very right, I've gotten very busy with a bunch of other projects and don't have the time to properly maintain this repo myself. I'm happy to add @ChrisCummins and @dgcrouse as maintainers here.

In my mind some additional features that would be nice to have are:
- cuDNN support (but models trained with cuDNN should still be usable without a GPU)
- Support for word tokens
- Better unicode support
- Better checkpointing system / specification (but should maintain backwards compatibility to avoid breaking checkpoints that have already been trained)

**Comment by dgcrouse** [comment]
I would love to tackle cuDNN support (working on my fork, though compatibility with CPU training is a work in progress), word tokens (pretty much done), improved unicode support (somewhat implemented in my fork).

As for checkpointing, I am working on some new features, but they are fundamentally incompatible with the old format. Maybe a Python script to upgrade old checkpoints?

I really think that checkpoints should be divided into 2 separate JSON files, one to resume from and one containing nitty-gritty stats. That way resuming will take less time and users can delete the stats checkpoints they don't need. Additionally, I think that checkpoint interval should be allowed to be specified in either batches or epochs.

Python 3 is not one of my strong points. I'm still staunchly in Py2 camp (messing with integer math truncation, grumble grumble), so I definitely cannot tackle that one. Maybe hold off though until the other preprocessing tasks are done?

Also on my list for improvements I would like to see is LMDB/LevelDB support in addition to HDF5. That would really make the training fly.

**Comment by ChrisCummins** [comment]
Great, thanks @jcjohnson. My main priorities are bug and compatibility fixes, and keeping the issue tracker alive.

I'm aware there is a test suite, but have never had cause to run it. I will look setting up Travis CI, as I think that automated testing on PRs will be helpful for keeping on top of (potentially breaking) changes.

@dgcrouse I will be your pro-Python3 counterpart. Py2 is dead ([almost](https://pythonclock.org/) 😉), and Py2/3 compatibility is best done sooner rather than later.

I see no problem in backward compatibility breaking changes to checkpoints, providing that checkpoint files have a version token embedded in them, and there is a suitable `./scripts/migrate-checkpoints.py` script to point users to checkpoint restoring fails across versions.

Closing this as "solved". Let's move new feature discussions into separate issues.
