### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by fusiller** [jcjohnson/torch-rnn#18]
Never found the exact way to just say thank you on Github.
Maybe it is missing some basic "like" button :)

So here it is : thank you for sharing this amazing work.

Alex

**Comment by obvio171** [comment]
+1

**Comment by jcjohnson** [comment]
I'm glad you're enjoying it!

**Comment by le-scientifique** [comment]
:+1:

**Comment by mrmartin** [comment]
Great stuff, thanks too!
Github does have a "like", it's the star button (top right).
Here's more info: [https://help.github.com/articles/about-stars/](https://help.github.com/articles/about-stars/)

**Comment by fusiller** [comment]
Thank you for pointing this out. I never noticed the stars ... Shame on me.
