### ISSUE TITLE
passing multiple input vectors / audio frames in VanillaRNN 

### ISSUE THREAD

**Issue by saurabhvyas** [jcjohnson/torch-rnn#199]
I am not able to understand how I can use VanillaRNN to input a series of vectors ( say I want to pass 5 vectors as a single input to all hidden layer ) , I read the documentation , I only  found following parameters 

sequence size ( to unroll )
Input dimension ( D )
Batch size
Hidden Size

**Comment by dgcrouse** [comment]
To do so, you could write your own preprocessing script to concatenate all the vectors into a single vector, then place them all into a unicode file. That is the only way this is supported.
