### ISSUE TITLE
Running in CPU mode (-GPU -1) but it's still looking for cutorch?

### ISSUE THREAD

**Issue by lilybradic** [jcjohnson/torch-rnn#209]
After training the network with -GPU -1, it's still looking for cutorch when I try to generate an output — any idea what I can do about this? (And are the errors under stack traceback related to this too?)

Struggling here - any help would be greatly appreciated :) thanks

`/Users/lily_bradic/torch/install/bin/luajit: ...s/lily_bradic/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cutorch' not found:No LuaRocks module found for cutorch
	no field package.preload['cutorch']
	no file '/Users/lily_bradic/.luarocks/share/lua/5.1/cutorch.lua'
	no file '/Users/lily_bradic/.luarocks/share/lua/5.1/cutorch/init.lua'
	no file '/Users/lily_bradic/torch/install/share/lua/5.1/cutorch.lua'
	no file '/Users/lily_bradic/torch/install/share/lua/5.1/cutorch/init.lua'
	no file './cutorch.lua'
	no file '/Users/lily_bradic/torch/install/share/luajit-2.1.0-beta1/cutorch.lua'
	no file '/usr/local/share/lua/5.1/cutorch.lua'
	no file '/usr/local/share/lua/5.1/cutorch/init.lua'
	no file '/Users/lily_bradic/.luarocks/lib/lua/5.1/cutorch.so'
	no file '/Users/lily_bradic/torch/install/lib/lua/5.1/cutorch.so'
	no file './cutorch.so'
	no file '/usr/local/lib/lua/5.1/cutorch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	...s/lily_bradic/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	sample.lua:24: in main chunk
	[C]: in function 'dofile'
	...adic/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010e48b9f0
`

**Comment by jeff-v** [comment]
I had the same problem, you need to append -gpu -1 to the output command since it tries to use a GPU to output as well as train.

**Comment by lilybradic** [comment]
This worked, thank you!
