### ISSUE TITLE
How to extend this code to deal with variable length squences?

### ISSUE THREAD

**Issue by jundeng86** [jcjohnson/torch-rnn#21]
Hi jcjohnson,

First of all, thanks for sharing!

I'm looking for a way of using this fast rnn code for speech processing. But it seems that the current code only works for fixed length sequences. Do you know how to extend it for variable length sequences? Thanks!

BTW, is there a typo at row 105 of VanillaRNN.lua? : "h: Sequence of hidden states, of shape (**T, N**, H)" => (**N, T**, H)?

Best,
Jun

**Comment by jcjohnson** [comment]
The current code will work fine if the sequence length varies from batch to batch. That will cause a little bit of memory allocation which will cause a small performance hit, but probably not too major.

If you wanted to handle differently sized sequences within the same minibatch, it would depend a bit on the task. If you wanted to do language modeling on short sequences of variable length, like you might see in image captioning, then I'd write a "masked" criterion that only back-propagated errors on certain timesteps of each sequence, allowing you to unroll a minibatch to a fixed length but ignore the junk outputs at the end of the shorter sequences. For an example of this approach you can see the image captioning question in the [third assignment for cs231n at Stanford](http://cs231n.github.io/assignments2016/assignment3/).

If you wanted to use the final hidden state to make some prediction about a sequence, I'd write a module that plucked out the proper final hidden state from each sequence; it might take a batch (N, T, H) of hidden states and a integer list of length N of sequence length, and return a tensor of shape (N, H) giving the final hidden state for each element in the input list.

You're right about the typo; fixed now. Thanks!

**Comment by jundeng86** [comment]
Thanks for your reply. What I am expecting is the second module you said. Such module can allow the current rnn code to work for speech process applications like speech enhancement.

**Comment by 3rd3** [comment]
@jcjohnson, what would you advice in the case of sequences with quite different lengths like this:

![output](https://cloud.githubusercontent.com/assets/2372391/15624151/c49f74d6-2480-11e6-9ba7-49132e1f5553.png)

Should I bundle sequences of similar length in batches? Couldn't one train it just the same way as the Shakespeare data set, but simply clear the hidden state on particular inputs e.g. on the character `#`.
