### ISSUE TITLE
HDF5 No accessibility and not valid?

### ISSUE THREAD

**Issue by weemeghann** [jcjohnson/torch-rnn#212]
First here's a pastebin of the full command and the error it caused.

https://pastebin.com/9E6XaEnn

So how do I fix this? The code has worked in the past so this is a little confusing! Sorry, I'm a beginner..

**Comment by dgcrouse** [comment]
Did you generate the HDF5 files you are trying to access? Also make sure the permissions are set correctly so that the files can be opened by your account.

**Comment by weemeghann** [comment]
Solved the problem, I had the files in the wrong place like a melon
