### ISSUE TITLE
Deterministic output of sample.lua with -start_test flag

### ISSUE THREAD

**Issue by turbotas** [jcjohnson/torch-rnn#217]
Wow - great performance update on char-rnn - thanks for this!
When using **sample.lua** with the _start_text_ flag, I would expect the output to be deterministic - i.e. produce the same output each run for the same checkpoint file and same start_text flag value?  Instead it's different output every time. Is there any way to get deterministic output - yes I know this might sound like an odd question!

**Comment by rabinandan** [comment]
Hi ! I am also wondering for same. Why execution of same checkpoint model produces different results in different run with same length ?

**Comment by antihutka** [comment]
By default, the next character is sampled from the distribution predicted by the model. You can use _-sample 0_ to pick the highest probability character at every timestep, but you're likely to get boring/repetitive results.

**Comment by turbotas** [comment]
I think the answer is more complex. It's more likely that an RNG is not
seeded the same for each run. char-rnn does seem to use the same seed.

On 21 Feb 2018 11:57 am, "antihutka" <notifications@github.com> wrote:

By default, the next character is sampled from the distribution predicted
by the model. You can use *-sample 0* to pick the highest probability
character at every timestep, but you're likely to get boring/repetitive
results.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jcjohnson/torch-rnn/issues/217#issuecomment-367303737>,
or mute the thread

**Comment by antihutka** [comment]
Looks like you're correct, char-rnn allows you to specify seed. It should be easy to implement it in torch-rnn.
https://github.com/karpathy/char-rnn/blob/master/sample.lua#L80

**Comment by ChrisCummins** [comment]
@antihutka hit the nail on the head. Set a manual seed. If you think it'd be a useful feature for others, wrap it behind a `-seed` flag and submit a PR :)

**Comment by turbotas** [comment]
Done, submitted a PR.  Never written a line of lua before ;-)
