### ISSUE TITLE
Sampling ouputs garbage, encoding problem?

### ISSUE THREAD

**Issue by wohnjayne** [jcjohnson/torch-rnn#24]
My model outputs only garbage when sampling (tiny shakespeare):
`th sample.lua -checkpoint cv/checkpoint_4000.t7 -length 500`
```
yAmPhaiOp!Rhe.c&Mr;vSghiBKXezpy me Bfe;
WZP:LMa.XZodWeF'
zux'd I reaRecheboKhxFk3So go ear h,UdFyboxRfZvEHxapJzPpy qmZYBHYQ SwR ze? fra 
...
```
I followed the installation procedure, prepared the tiny shakespeare data and trained the model as explained.

*prepro*
`python scripts/preprocess.py --input_txt data/tiny-shakespeare.txt --output_h5 data/tiny-shakespeare.h5 --output_json data/tiny-shakespeare.json`

*training*
`th train.lua -input_h5 data/tiny-shakespeare.h5 -input_json data/tiny-shakespeare.json`

training is blazingly fast, but when sampling, the model outputs garbage, even when trained longer (e.g. 17k steps, i.e., 50 epochs). At 4000 steps  [char-rnn](https://github.com/karpathy/char-rnn) outputs are great already.

Am I missing something obvious?

**Comment by jcjohnson** [comment]
Hmm, I just tried to train a model again on tiny-shakespeare and I'm getting the same garbage outputs that you are. I may have accidentally introduced a bug recently; I'm looking into it.

**Comment by jcjohnson** [comment]
I think that I accidentally broke the LanguageModel in https://github.com/jcjohnson/torch-rnn/commit/cc52203e36ba07b91018ee938bac0ae9810d9c97. I've reverted the file for now, which should fix the problem you're seeing.

Thanks for pointing this out!

**Comment by siddharthgee** [comment]
Just confirming, I had the same problem and the revert fixed it. At 3000, the output looks beautiful.

ixt, that I could dream, young.

YORK:
Destroy'd, Cale:
I should fore storms that head, let them
As you only with wax plucking words,
Even well, and one words:--
Fiefold that need believe that dareth will to's business: make me wail your part.

KING RICHARD III:
Norant what forswear, stood slaughter, like those treasons and love withal, that I netemper'd,
Our men shall be tangle. Bear a guest:
I am not fair foes.

LUCIO:
Good pity should break the Duke of Turgo.

QUEEN MARGARET:
Alas, he shall h



Thank you Justin.

**Comment by wohnjayne** [comment]
great, thanks for looking into this so quickly!
