### ISSUE TITLE
scripts/preprocess.py--encoding flag not documented

### ISSUE THREAD

**Issue by casey** [jcjohnson/torch-rnn#26]
The `--encoding` flag isn't documented. It should probably be added to flags.md.

Thanks for this!

**Comment by casey** [comment]
Also, a separate but related issue, it looks like that high bytes appear as "[N]" in the output. There should probably be an option to turn them back into the bytes they represent when sampling.

**Comment by dgcrouse** [comment]
We are rewriting the preprocessing script to address this.
