### ISSUE TITLE
preprocess.py uses np.uint32 when there are 256 items in the vocabulary

### ISSUE THREAD

**Issue by casey** [jcjohnson/torch-rnn#27]
256 different values should fit in a byte, but I believe this line has a bug, and goes to uint32 when there are more than 255:

https://github.com/jcjohnson/torch-rnn/blob/master/scripts/preprocess.py#L47

**Comment by casey** [comment]
I was just thinking about this, and I realized that it's probably because lua indices start at 1.

**Comment by jcjohnson** [comment]
Yep that's right.
