### ISSUE TITLE
sample.lua flag of -sample 0 raises error

### ISSUE THREAD

**Issue by buckohfive** [jcjohnson/torch-rnn#28]
Hi!

I've been working with this code for a few weeks now, and it's fantastic!  I've found a possible issue - when I pass a -sample 0 flag to sample.lua (to force argmax output vice softmax), it fails with the following error:

~/torch-rnn$ th sample.lua -checkpoint /tmp/cp_512_2_130800.t7 -length 20000 -sample 0
~/torch/install/bin/luajit: ./LanguageModel.lua:185: bad argument #1 to 'copy' (torch.*Tensor expected, got nil)
stack traceback:
	[C]: in function 'copy'
	./LanguageModel.lua:185: in function 'sample'
	sample.lua:41: in main chunk
	[C]: in function 'dofile'
	...five/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405ea0

**Comment by jcjohnson** [comment]
Sorry about that! Should be fixed in https://github.com/jcjohnson/torch-rnn/commit/b77a8b70435a901a1e85f86027a7c971ba76a518

**Comment by buckohfive** [comment]
Justin -

No need to apologize. You provide excellent code for the community to use.
Thank you!
