### ISSUE TITLE
torch-rnn does not make use of multiple CPU cores

### ISSUE THREAD

**Issue by AlekzNet** [jcjohnson/torch-rnn#34]
I've got a 4 core CPU with hyper-threading and no GPU. With char-rnn htop shows, that all 8 threads are almost 100% busy, but torch-rnn uses only one thread (all other cores are completely idling), what makes it several times slower than char-rnn (in the CPU only mode). Is it possible to add multi-core support to torch-rnn?

**Comment by jcjohnson** [comment]
Neither char-rnn nor torch-rnn have any explicit code to handle multi-core; both should be handled by BLAS bindings in Torch. Are you using the same Torch install for both?

**Comment by AlekzNet** [comment]
Yes, you are right! The versions were indeed different. char-rnn was running under the old one. When I upgraded to the latest available packages, char-rnn began to show the same behaviour. Now, instead of 31sec per batch, it takes 1200sec, what makes any of the programs effectively useless...  :(

**Comment by AlekzNet** [comment]
I completely removed torch and reinstalled it from scratch. It looks completely different now! Now I see, that torch-rnn is indeed much faster and uses much less memory! Thanks much!

**Comment by micool91** [comment]
@AlekzNet 

So it worked on multiple cores, or not?

**Comment by AlekzNet** [comment]
Yes, it uses as many cores as you specify in the OMP_NUM_THREADS variable. I do not understand why sometimes it uses only one core, but recompiling torch (once I had to completely remove OpenBLAS and Torch) helps.

In other words, it's not torch-cnn what needs tuning, but OpenBLAS and torch.

**Comment by AlekzNet** [comment]
Before compiling OpenBLAS and torch, i use the following settings:

export OMP_NUM_THREADS=4
export USE_OPENMP=1

**Comment by micool91** [comment]
Thanks, now it worked for me too :)

**Comment by prontiol** [comment]
Does not work for me.
Test program utilizes all the cpu cores:
```python
import numpy as np
size = 10000
a = np.random.random_sample((size, size))
b = np.random.random_sample((size, size))
n = np.dot(a,b)
```
so I assume, OpenBLAS and Numpy are configured correctly.
Can someone advise?

**Comment by prontiol** [comment]
I managed to solve the problem.
My `torch` module was built without OpenBLAS support because it could not find it.
Adding path to OpenBLAS (`/opt/OpenBLAS/lib` in my case) to the `CMAKE_LIBRARY_PATH` and `LD_LIBRARY_PATH` environment variables and rebuilding torch7 fixed the problem.

**Comment by stuarthayhurst** [comment]
I know that I'm horribly late to this thread, but may I ask which version of torch you had to use to get it to work or what the final solution was? Thanks.

**Comment by prontiol** [comment]
@Dragon8oy It was just an experiment, I don't have this project anymore and can't check the version. Sorry about that.

**Comment by stuarthayhurst** [comment]
@prontiol Thanks, hopefully someone else can help.

**Comment by AlekzNet** [comment]
A couple of weeks ago I recompiled both OpenBLAS and torch (latest versions). Works fine. Before recompilation only one thread was used. I would recommend to start from scratch. Compile OpenBLAS first with:

export OMP_NUM_THREADS=4
export USE_OPENMP=1

Then compile torch.
