### ISSUE TITLE
libhdf5-dev unavailable on latest Ubuntu?

### ISSUE THREAD

**Issue by Patashu** [jcjohnson/torch-rnn#39]
I was trying to install this today, and 'sudo apt-get install libhdf5-dev' failed with "Unable to locate package libhdf5-dev". Apparently libhdf5-dev doesn't exist at all on the most recent Ubuntu version, or something like that? Is there any good workaround for this? I'm a linux newbie so I could be overlooking something.

**Comment by gokceneraslan** [comment]
Enable universe repository: http://askubuntu.com/a/148645/118413

**Comment by Patashu** [comment]
TY for the prompt response, I'll try this next time.

**Comment by jgalaz84** [comment]
Even after enabling all repositories, I still get "E: Unable to locate package libhdf5-8"
