### ISSUE TITLE
Sample h5 and json files don't work

### ISSUE THREAD

**Issue by jeffThompson** [jcjohnson/torch-rnn#44]
I believe the sample `tiny_shakespeare.h5` and `tiny_shakespeare.json` files are from an earlier version of this repo and will break when training. I re-ran the `processor.py` script and it now works.

**Comment by jcjohnson** [comment]
The repo only ships with a `.txt` version of the dataset; you must have created the `.h5` and `.json` versions yourself.

**Comment by jeffThompson** [comment]
Ah! Maybe when running the `preprocess.py` without any arguments? I thought it said somewhere it pulls from the `tiny_shakespeare.txt` file?
