### ISSUE TITLE
Using non-ASCII characters in start_text crashes sample.lua

### ISSUE THREAD

**Issue by tmp6154** [jcjohnson/torch-rnn#47]
Having non-ASCII characters in arguments, particularly UTF-8 which is my terminal encoding breaks sample.lua start_text functionality. Here's sample output, where i try to initialize network with russian word for "test":

```
th sample.lua -checkpoint models/test/checkpoint_27350.t7 -length 1000 -sample 1 -gpu -1 -temperature 1 -start_text тест
/home/vostrosa/torch/install/bin/luajit: ./LanguageModel.lua:129: Got invalid idx
stack traceback:
        [C]: in function 'assert'
        ./LanguageModel.lua:129: in function 'encode_string'
        ./LanguageModel.lua:174: in function 'sample'
        sample.lua:41: in main chunk
        [C]: in function 'dofile'
        ...ator/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405ec0
```

This is very unfortunate, since most of datasets I train network on consist mostly of Russian UTF-8 encoded text and I'm unable to preseed the network. My guess is that it treats UTF-8 as a single-byte encoding, which would explain why it yields invalid indices.

**Comment by AlekzNet** [comment]
Can you try KOI8?

**Comment by tmp6154** [comment]
Yeah, I thought to use KOI8-R or CP1251 and do character reencodings myself (perhaps, with a python script).

But now I tried it with KOI8-R dataset and KOI8-R encoded start_text and got same error. Looks like it doesn't like any non-ASCII characters, even on single-byte encodings.

**Comment by AlekzNet** [comment]
Can you check the  input_json file? Does it have correct indexes/tokens in both idx_to_token and token_to_idx arrays?

**Comment by tmp6154** [comment]
Weird. I can see unicode tokens in json file, such as

```
{"1": "\u042d", "2": "\u041f", "3": "\u0418", "4": "\u0417", "5": "\u041e", "6": "\u0414"
```

But I'm certain the file I preprocessed was KOI8-R

python ./scripts/preprocess.py --input_txt data/enctest/inputkoi8r.txt --output_h5 enctest.h5 --output_json enctest.json --encoding koi8-r
Total vocabulary size: 140
Total tokens in file: 416694
  Training size: 333356
  Val size: 41669
  Test size: 41669
Using dtype  <type 'numpy.uint8'>

**Comment by cgadgil** [comment]
You can use char-rnn for the time being since char-rnn seems to honor Unicode fine.

**Comment by AlekzNet** [comment]
Another solution: https://github.com/jcjohnson/torch-rnn/pull/12

**Comment by tmp6154** [comment]
I don't exactly get how PR12 solves this problem.

**Comment by AlekzNet** [comment]
It depends if this issue is "lua only", or it's somewhere between how python creates token_to_idx and how lua interprets the start_text. PR12 gets rid of python and moves everything into one single lua domain.

**Comment by tmp6154** [comment]
No, it's clearly lua-only issue. Tokens are stored as double-byte unicode values. It's just Lua has no knowing of how to map UTF-8 encoded arguments from command-line to double-byte unicode token values. All it could see are single bytes outside (>127) ascii range. It couldn't figure out that UTF-8 bytes must be interpreted together, not on single-byte basis. It seems to know only ascii encoding natively. So, moving everything to lua would make no difference.

But thanks to @maraoz , this problem is resolved, by using UTF-8 library, torch-rnn is now capable of correctly interpreting UTF-8 encoded command-line arguments. All that left is to merge this pull request.

**Comment by jtippett** [comment]
Not a fix, but if you don't really mind losing the unicode, one can quickly strip unicode with this command: `iconv -c -f utf-8 -t ascii corpus.txt > corpus-ascii.txt`, and then run the rnn on the stripped file.

**Comment by hooande** [comment]
I'm having this same problem. I don't know if anyone else has this use case, but I'm trying to encode a list of 160 possible actions as individual characters. This is bigger than the ascii range so I use utf8. The model trains, but like @tmp6154 I can't initialize the start_text param with utf8 input to sample it, either from the command line or reading from a file in sample.lua.

I still don't understand the solution proposed above, but it would be nice if it were merged in. It seems odd that I can train the model with utf8 chars, but can't initialize a sample with the same encoding.

**Comment by tmp6154** [comment]
Actually, it's pretty simple if you think about it. Encoding, such as UTF-8, maps characters to numbers. Neural network doesn't know anything about characters, it operates on numbers. preprocess.py takes the text in any encoding Python supports (including UTF-8 encoded text) and basically, creates a brand new, reduced encoding off base encoding which contains only characters contained within corpus (in order they were encountered in the text).

Now, all information that is required for training and sampling is available - everything is stored in output JSON and "text" (that is, sequence of tokens from JSON) is stored in h5. UTF-8 chars actually get transformed into single unicode codepoint (which, I believe, is different from Karpathy's char-rnn, which treated separate UTF-8 bytes as individual characters, leading to invalid UTF-8 sequences in samples) and are mapped to some integer number.

During training phase, neural network receives only integer numbers, representing the characters. It doesn't know anything about encoding they were in. For example, in one of my datasets, letter "a" has code 85, while in UTF-8, it's 97. I.e, UTF-8 is not used at all during the training, it's our derived encoding, that was produced with preprocessor. That means that when training sees a letter "a", input neuron for 85 will be activated.

Same applies to sampling phase, actually. To generate samples, sample.lua doesn't need to know UTF-8. It just does a forward pass of neural network, looks, which checks, which character number is next, and then maps it back to the original encoding (as found in JSON file).

The reason, why start_text couldn't be initialized from UTF-8 is because Lua (unlike Python) doesn't come "with batteries included", that is, to support UTF-8 text, a third party library is needed. It couldn't find matching Unicode codepoints to map them into numbers for JSON and tries to interpret start_text as 8-bit encoding.

Justin is probably busy for now, in meanwhile, you could either apply the patch from PR #52, or checkout the [fork](https://github.com/tmp6154/torch-rnn) I made, where I've already applied that (and a few other) patches. Hopefully, these patches will be merged into mainline in the future.

**Comment by hooande** [comment]
I found the fork in your repo, it works.

Thanks a lot for this. I was stuck on this problem for days and now I am
happily making predictions. Cheers!

**Comment by tmp6154** [comment]
No problem, enjoy! Actually, thanks for fixing that particular problem goes to @maraoz, he made that pull request, which I applied against my repo.

**Comment by smartynov** [comment]
I run into the same problem and found an easy hack to overcome this. You can replace `LM:encode_string` method in `LanguageModel.lua` to the following version:

```lua
function LM:encode_string(s)
  local encoded = torch.LongTensor(#s)
  local token = ''
  local ei = 1
  for i = 1, #s do
    token = token .. s:sub(i, i)
    local idx = self.token_to_idx[token]
    if idx ~= nil then
      encoded[ei] = idx
      token = ''
      ei = ei + 1
    elseif #token == 4 or i == #s then
      assert(idx ~= nil, 'Got invalid idx')
    end
  end
  encoded:resize(ei-1)
  return encoded
end
``` 

It scans for multibyte keys in token_to_idx table. I'm not sure if it is clean enough, but maybe @jcjohnson will take a look and incorporate it.

**Comment by dgcrouse** [comment]
We are rewriting the preprocess.py script to be much more robust and take into account up to utf-32.

**Comment by lagleki** [comment]
Even "@@@ " in -start_text raises this error.
