### ISSUE TITLE
Install tutorial for Mac users

### ISSUE THREAD

**Issue by jeffThompson** [jcjohnson/torch-rnn#48]
I've written up a rather detailed set of installation instructions for Mac users:
http://www.jeffreythompson.org/blog/2016/03/25/torch-rnn-mac-install/

If this is helpful in any way, please feel free to link to and/or use!

**Comment by jcjohnson** [comment]
This is great - thanks! I added a link to the installation section.

**Comment by jeffThompson** [comment]
Thank _you_ for the great tool!
