### ISSUE TITLE
Memory allocation/leak issue

### ISSUE THREAD

**Issue by buckohfive** [jcjohnson/torch-rnn#50]
This is a weird one, and took me a while to track down. I believe torch/torch-rnn has a memory leak that survives the process ending (?!).  Crazy talk, I know - but try the following:

1. Train a network, any network.

2. In a terminal, run 'top'

3. Create a loop of hundreds or thousands of sample actions (I was running 'th sample.lua -checkpoint words/20160323-0001/cv/cp_w512_d2_s3_b10_1000.t7 -start_text "hgiusdhss unwiieorw 99jsowlr4 " -length 135 -temperature 1' and comparing subtle variations in output)

4. Watch memory creep up.  On my system, it takes about 95-105 iterations for total memory usage to creep from less than 1 GB to *GB, and to start using swap.  I can do this in under two minutes.

I've waited hours and days for the allocated memory to free up, and it doesn't.  Luajit/Lua is not running in any way.  If I let this go on long enough, Ubuntu starts killing processes due to lack of memory - eventually the system halts or I reboot it. 

My system has 8 GB of RAM and a Nvidia GTX 750 Ti GPU, is running Ubuntu 15.10, and is using gcc/g++ 4.9.3 with NVIDIA 352.63, Cuda 7.5.18 and CudNN 4.0.  I installed torch7 from the git repo, and installed it with alternately luajit 2.1rc1 and lua52 - both display this issue.

I noticed this first when sampling trained networks, but I believe it occurs in training as well - its harder to detect because training iterations are far longer.

**Comment by tmp6154** [comment]
Judging by your description, that sounds like kernel-mode memory leak, since keeping allocated memory after process ending would be not safe and would open the vector to perform DoS attack.

It could be, for instance, a faulty driver allocating excess memory and not freeing it up. Try using

sudo slabtop

It should give info on kernel-mode memory usage. It should not normally take up more than several hundreds of MBs (my machine keeps 200). If it takes a GB or more, there must be something bad going in kernel-space (nvidia drivers leak kernel memory?).

**Comment by buckohfive** [comment]
Interesting.  The total space used under slabtop isn't much (~150MB) but running the sample.lua repeatedly caused _hundreds of thousands_ of kmalloc-32 objects to be allocated and not destroyed (right now, my dev box has 1.47M kmalloc-32 objects).

**Comment by buckohfive** [comment]
Further testing.  I can cause this memory leak to occur using either char-rnn or torch-rnn.  Using keras (Theano), I don't get the same issue with similar networks.  

I also note that the memory leak is consistent - 110 objects (ish - sometimes 111, sometimes 109) of 128 bytes each, regardless of network size.

Weird.  I'm not sure how to proceed from here.

**Comment by buckohfive** [comment]
This is a cutorch error most likely.  In sample.lua, if i halt execution error() after "require 'cutorch'", I can cause the memory leak.  Before "require 'cutorch'", no leak.

I'll close this issue.  It isn't torch-rnn :)

**Comment by buckohfive** [comment]
I put this over in cutorch, FYI: https://github.com/torch/cutorch/issues/379
