### ISSUE TITLE
cannot convert 'struct THCudaTensor *' to 'float'

### ISSUE THREAD

**Issue by zfrenchee** [jcjohnson/torch-rnn#56]
I'm just trying to set this up and when I go to run `train` I run into this issue:

```
Running with CUDA on GPU 0
/home/alex/torch/install/bin/luajit: /home/alex/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
/home/alex/torch/install/share/lua/5.1/nn/THNN.lua:109: bad argument #5 to 'v' (cannot convert 'struct THCudaTensor *' to 'float')
```

Seems like someone made this an issue on the torch/nn repo: https://github.com/torch/nn/issues/694
Any ideas?

**Comment by jcjohnson** [comment]
Try reinstalling torch, cutorch, nn, and cunn.

**Comment by zfrenchee** [comment]
This seems to have worked.

**Comment by marvin521** [comment]
@zfrenchee how did you solve the problem?  reinstall the packages pointed by @jcjohnson?
