### ISSUE TITLE
The initial bias of the forget gate

### ISSUE THREAD

**Issue by AlekzNet** [jcjohnson/torch-rnn#63]
I'm still trying to understand how it all works together. A question: how/where is the initial bias of the forget gate set? According to some papers (e.g. http://www.datascienceassn.org/content/empirical-exploration-recurrent-network-architectures), it should be set between 1 and 2 to "encourage learning". In char_rnn it's set to 1. But I can't find it in torch_rnn.

**Comment by jcjohnson** [comment]
The bias of the forget gate is set to 1 here:

https://github.com/jcjohnson/torch-rnn/blob/master/LSTM.lua#L54

**Comment by AlekzNet** [comment]
Oh, I missed  self:reset() in layer:__init ... :) 

Thanks Justin!
