### ISSUE TITLE
About Multi-threading 

### ISSUE THREAD

**Issue by already-taken-m17** [jcjohnson/torch-rnn#70]
Is this project multi-threaded ?
if no, then can someone guide me how to make this multi-threaded ?

**Comment by jcjohnson** [comment]
Most of the computational overhead here is from matrix multiplications inside the RNNs, and torch matrix multiplication relies on the underlying BLAS installation for multithreading.

If you are using OpenBLAS (which is the default for torch) then you can set the number of threads by setting an environment variable:

https://github.com/xianyi/OpenBLAS#usages

**Comment by already-taken-m17** [comment]
Thanks, done.
