### ISSUE TITLE
Generated "text" always look like "start_text'

### ISSUE THREAD

**Issue by vinhqdang** [jcjohnson/torch-rnn#78]
Hello all

I observe a strange thing: after training a model, I tried:

``th sample.lua -checkpoint ... -length 5 -start_text "abcde"``

then the generated text will be *abcde*. I tried with different *start_text* parameter, but it always like this.

Is it usual?

P/S: if I set *-length* to a number which is less than the length of *start_text* (for instance, in above example, if I set ``-length 3``, an error will appear). Is it normal?

Thanks

**Comment by jcjohnson** [comment]
Yes, that is expected. `-start_text` is the text that will be at the beginning of the generated sequence.

Crashing when `-length` is shorter than `-start_text` is also expected, but I should probably fix this with an assert.
