### ISSUE TITLE
How could I know the name of t7 file after training

### ISSUE THREAD

**Issue by vinhqdang** [jcjohnson/torch-rnn#79]
Hello

After training, is there a way to know the name of the last **.t7** file generated, then I can run *sample.lua* automatically.

I know it is possible via programming, such as find the latest file which is created with the *checkpoint* prefix etc. but is there an official way from torch-rnn?

Thanks

**Comment by jcjohnson** [comment]
There isn't anything built-in to let you do exactly that, but the filenames are just a combination of the `-checkpoint_name` flag and the iteration number so you could get the most recent checkpoint just by looking at the filenames; you don't need to look at the timestamp.
