### ISSUE TITLE
Sample text in CPU-only mode from checkpoint generated with GPU?

### ISSUE THREAD

**Issue by kadamwhite** [jcjohnson/torch-rnn#80]
[char-rnn warns that there are issues](https://github.com/karpathy/char-rnn#sampling) if you try to sample in CPU-only mode from a checkpoint that was generated on a GPU; the readme demonstrates a conversion script:

> **Training with GPU but sampling on CPU.** Right now the solution is to use the `convert_gpu_cpu_checkpoint.lua` script to convert your GPU checkpoint to a CPU checkpoint. In near future you will not have to do this explicitly. E.g.:
>
> ```
> $ th convert_gpu_cpu_checkpoint.lua cv/lm_lstm_epoch30.00_1.3950.t7
> ```
>
> will create a new file `cv/lm_lstm_epoch30.00_1.3950.t7_cpu.t7` that you can use with the sample script and with `-gpuid -1` for CPU mode.

I trained on AWS with CUDA, and after moving the checkpoints down to an integrated graphics laptop I get this error:

```
th sample.lua -checkpoint cv/checkpoint_1700.t7 -length 1000 -gpu -1
/Users/kadam/torch/install/bin/luajit: cannot open </Users/kadam/torch/torch-rnn/cv/checkpoint_1700.t7> in mode r  at /Users/kadam/torch/pkg/torch/lib/TH/THDiskFile.c:649
stack traceback:
	[C]: at 0x0ef28fa0
	[C]: in function 'DiskFile'
	/Users/kadam/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	sample.lua:19: in main chunk
	[C]: in function 'dofile'
	...adam/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010ec05d10
```
Given the char-rnn note I wondered if this was due to a need to convert in a similar fashion, but I cannot find a comparable script or related documentation within torch-rnn. Am I doing something else wrong?

**Comment by jcjohnson** [comment]
torch-rnn saves checkpoints in a slightly different way from char-rnn, so there is no need to run a conversion script if you want to sample on CPU from a checkpoint trained on GPU; something else must be going wrong.

It looks like Lua can't find the file; are you sure you have the path right? Sometimes Lua has a hard time with `~` for your home directory, so you may have to use a full absolute path. You can try debugging in the Torch REPL by running something like this from the torch-rnn root directory:

```
th
th> require 'LanguageModel'
th> path = '/Users/kadam/torch/torch-rnn/cv/checkpoint_1700.t7'
th> checkpoint = torch.load(path)
```

**Comment by kadamwhite** [comment]
Thank you for the quick response. I must have been typing something wrong, it is now sampling as expected from the provided checkpoint. Much appreciated!

**Comment by xzava** [comment]
For anyone else, I had a similar problem.

"cannot open <cv/checkpoint_10000.t7> in mode r"

after running the suggested sample code
`th sample.lua -checkpoint cv/checkpoint_10000.t7 -length 2000 -gpu -1`

The problem is, the code saves a checkpoint every 1000 iterations and the default sample code is for 10,000 iterations. 

Change this the sample code to the correct iteration file found in cv/

eg.
`th sample.lua -checkpoint cv/checkpoint_1000.t7 -length 2000 -gpu -1`

NOTE: This is the CPU example see this flag --> `-gpu -1`
