### ISSUE TITLE
Does torch-rnn distinguish lower and upper case?

### ISSUE THREAD

**Issue by vinhqdang** [jcjohnson/torch-rnn#96]
Today I train a text file, which I believe that there are 50 different symbols (from a..z A..Z and 0,1)

However, the ``train.lua`` reported that

``Total vocabulary size: 25``

Does ``torch-rnn`` distinguish between ``a`` and ``A``? Well, I can test by myself, but wanna ask from experts too.

**Comment by jcjohnson** [comment]
It should distinguish between upper and lower case.
