### ISSUE TITLE
Why do we need to ``luarocks install torch`` at the beginning

### ISSUE THREAD

**Issue by vinhqdang** [jcjohnson/torch-rnn#99]
Hello

I do not understand the meaning of ``luarocks install torch``.

We install ``torch-rnn`` after installing ``torch7``. Why do we need to install ``torch`` again?

Thanks

**Comment by jcjohnson** [comment]
Torch pushes changes very frequently, so it is a good idea to reinstall it
from time to time to make sure you are on the latest version.

**Comment by vinhqdang** [comment]
It is very clear, thanks a lot,
